name: Clear needs-info/pr-unfinished on activity
jobs:
  clear-pr-unfinished:
    runs-on: self-hosted
    permissions:
      id-token: write
      issues: write
      pull-requests: write
    steps:
    - name: Remove label
      uses: actions-ecosystem/action-remove-labels@v1
      with:
        labels: |
          needs-info
          pr-unfinished
env:
  PYTHONPATH: /tmp/instr
  BASH_ENV: /tmp/instr/bash_env.sh
'on':
  pull_request:
    types:
    - synchronize
    - review_requested
  issue_comment:
    types:
    - created
  pull_request_review_comment:
    types:
    - created
