name: Close stale issues
permissions:
  issues: write
jobs:
  stale:
    runs-on: self-hosted
    steps:
    - uses: actions/stale@v10
      with:
        days-before-stale: 30
        any-of-labels: needs-info
env:
  PYTHONPATH: /tmp/instr
  BASH_ENV: /tmp/instr/bash_env.sh
'on':
  schedule:
  - cron: 50 5 * * *
